# Generated by Django 3.2.5 on 2022-07-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0002_jejuolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=14)),
                ('loc', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=9)),
                ('mgr', models.IntegerField(null=True)),
                ('hiredate', models.DateTimeField()),
                ('sal', models.IntegerField()),
                ('comm', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
    ]
