# Generated by Django 3.2.5 on 2022-07-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='cnt',
            field=models.IntegerField(null=True),
        ),
    ]
