# Generated by Django 3.2.5 on 2022-07-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_curriculum_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='cnt',
        ),
    ]
