# Generated by Django 3.2.5 on 2022-07-18 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_nm', models.CharField(max_length=50, null=True)),
                ('period', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'warranty',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.warranty'),
        ),
    ]
