# Generated by Django 3.2.5 on 2022-07-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_armyshop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armyshop',
            table='army_shop',
        ),
    ]
